### ISSUE TITLE
Training details

### ISSUE THREAD

**Issue by wqtwjt1996** [sniklaus/pytorch-hed#2]
Could you please provide the details of training your pytorch model? Thanks!

**Comment by sniklaus** [comment]
I just used converted weights from the official Caffe model: https://github.com/s9xie/hed

I always wanted to update this repository with a training section since I believe that our area has a better understanding of deep learning nowadays, which should make it possible to train an improved version.

**Comment by yuanjunchai** [comment]
So how to restart to train a new model?

**Comment by sniklaus** [comment]
The official repository has training details here: https://github.com/s9xie/hed#training-hed
