### ISSUE TITLE
BN layer

### ISSUE THREAD

**Issue by StephenZhao1** [sniklaus/pytorch-hed#26]
I have read some source code about many edge detection network, all of the network are without BN layer, why was that?

**Comment by sniklaus** [comment]
Thank you for your interest in this work! Please be aware that this is just an unofficial PyTorch re-implementation of the official Caffe one, so your question is probably better suited over [there](https://github.com/s9xie/hed) since I am afraid that I don't know why the authors made their decisions. :upside_down_face:
